### PR TITLE
Upgrade Ridley's chef client version to from 11.4.0 to 13.6.4

### PR DESCRIPTION
**Pull request by itmustbejj**
Signed-off-by: Josh Hudson <jhudson@chef.io>

### CODE REVIEW

**Comment by itmustbejj** [comment]
Addresses https://github.com/berkshelf/ridley/issues/374 and fixes a previously broken unit test due to Faraday's 0.13.1 update.

**Comment by itmustbejj** [comment]
@thommay @lamont-granquist Any concerns with this change to increase the chef-client version that Ridley sends in it's request headers?

**Comment by lamont-granquist** [comment]
ridley has been removed from berkshelf master and the next release won't have it at all

**Comment by thommay** [comment]
thanks @itmustbejj . As lamont says, we'll be killing ridley entirely next berkshelf release, but this is an improvement anyway :)

**Pull request merged**
