### PR TITLE
Support new cookbook metadata

### LINKED ISSUE #338: chef_version setting in cookbook metadata
If I set chef_version in metadata.rb, then I get the following error

    An error occurred while reading the Berksfile:

      Could not parse `~/cookbooks/test/metadata.rb': undefined method `chef_version' for #<Ridley::Chef::Cookbook::Metadata:0x007fc55a4f24d8>```

https://github.com/berkshelf/berkshelf/issues/1499

### PR DESCRIPTION
**Pull request by thommay**
Fixes #338

### CODE REVIEW

**Comment by lamont-granquist** [comment]
can we rub some method_missing on this to warn that there's new metadata?

**Comment by thommay** [comment]
@lamont-granquist done

**Comment by lamont-granquist** [comment]
:+1:

**Comment by bleything** [comment]
Hey, any chance you could cut a bugfix release with this fix? With chef pulling `apt_repository` into core and changing its behaviour I suddenly have a bunch of cookbooks that require a specific version of chef and berks blowing up in all of them.

**Comment by thommay** [comment]
@bleything done.

**Comment by bleything** [comment]
Thank you!

**Pull request merged**
